<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="mahlia" name="Verify The Search Suggestion" tests="1" failures="1" timestamp="16 Apr 2016 23:37:21 GMT" time="14.116" errors="0">
  <testcase name="verifySearchSuggestion" time="2.192" classname="ProductSearching.Searching">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
	at ProductSearching.Searching.verifySearchSuggestion(Searching.java:35)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- verifySearchSuggestion -->
</testsuite> <!-- Verify The Search Suggestion -->
